### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by ramseys1990** [LevinIgor/Medicine#4]
Hi, do you have the db schema available?

Thank you in advance!

**Comment by LevinIgor** [comment]
Hello, thanks for your interest. I didn’t think that anyone would be interested in the project, so I didn’t bother with the description. I added the schema.sql file (https://github.com/LevinIgor/Medicine/blob/main/schema.sql) copy it and paste it into the sql editor in the left column after you create the supabase project
